Resources:
  table8235A42E:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: "N"
      GlobalSecondaryIndexes:
        - IndexName: idIndex
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 10
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      TableName: Items
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: SetupStack/table/Resource
  ExampleIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: true
    Metadata:
      aws:cdk:path: SetupStack/ExampleIdentityPool
  CognitoDefaultUnauthenticatedRoleABBF7267:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud:
                  Ref: ExampleIdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: unauthenticated
            Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: SetupStack/CognitoDefaultUnauthenticatedRole/Resource
  CognitoDefaultUnauthenticatedRoleDefaultPolicy2B700C08:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - mobileanalytics:PutEvents
              - cognito-sync:*
            Effect: Allow
            Resource: "*"
          - Action: sns:Publish
            Effect: Allow
            Resource: "*"
          - Action: dynamodb:PutItem
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: CognitoDefaultUnauthenticatedRoleDefaultPolicy2B700C08
      Roles:
        - Ref: CognitoDefaultUnauthenticatedRoleABBF7267
    Metadata:
      aws:cdk:path: SetupStack/CognitoDefaultUnauthenticatedRole/DefaultPolicy/Resource
  DefaultValid:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId:
        Ref: ExampleIdentityPool
      Roles:
        unauthenticated:
          Fn::GetAtt:
            - CognitoDefaultUnauthenticatedRoleABBF7267
            - Arn
    Metadata:
      aws:cdk:path: SetupStack/DefaultValid
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAACl1PzQ7CIAx+Fu+s2xIT402zkyeX6QswQGUOakbRLIR3F7aL8fT9NV/bGupqD9XmwD+uEPJZBoGTgnAhLp6sUw79JBRrbvbs6eWJNWgdTV5Q9n7zFEhNGm1kuSvI2XKDsodw5f24jCwkMoF3qwkhJOsklSVNc4s4sj/d4aiOlA55mGRGprmBkM1ldcYWRy3mLFcWY2QWpYLBle96C7v02eC0LiafWo2CbsUv6QwnVvYAAAA=
    Metadata:
      aws:cdk:path: SetupStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  TableName:
    Value:
      Ref: table8235A42E
  Identitypoolid:
    Value:
      Ref: ExampleIdentityPool
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

